### ISSUE TITLE
Needs more instruction on how to run

### ISSUE THREAD

**Issue by Danwhy** [jmnr/dark#9]
We've followed all the instructions on the readme, but keep getting errors when we try to run the server.
We got the following error:
```
OpenError: IO error: ./mydb/MANIFEST-000014: No such file or directory
    at /Users/Daniel/projects/dark/node_modules/level/node_modules/level-packager/node_modules/levelup/lib/levelup.js:119:34
    at /Users/Daniel/projects/dark/node_modules/level/node_modules/leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:39:16
```
After creating a file called ./mydb/MANIFEST-000014 we got the next error:
```
OpenError: Corruption: no meta-nextfile entry in descriptor
    at /Users/Daniel/projects/dark/node_modules/level/node_modules/level-packager/node_modules/levelup/lib/levelup.js:119:34
    at /Users/Daniel/projects/dark/node_modules/level/node_modules/leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:39:16
```

**Comment by SimonLab** [comment]
The port is 8000 not 3000 and you  need to delete the leveldb folder to start the application
